# Generated by Django 5.0.7 on 2024-08-11 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='completado',
        ),
        migrations.RemoveField(
            model_name='juego',
            name='preguntas_respondidas',
        ),
        migrations.RemoveField(
            model_name='juego',
            name='tiempo_restante',
        ),
        migrations.AddField(
            model_name='juego',
            name='resultado_juego',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='juego.resultado'),
        ),
    ]
