# Generated by Django 5.0.7 on 2024-08-11 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0002_remove_juego_completado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='nivel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='juego.nivel'),
            preserve_default=False,
        ),
    ]
